mongo3:
  hostname: mongo3
  image: mongo:3.0.6
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27018:27017"
    - "28018:28017"
  container_name: mongo3
  volumes:
    - haostay_dev_mongo:/haostay_dev/mongo3
  restart: always

mongo2:
  hostname: mongo2
  image: mongo:3.0.6
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27019:27017"
    - "28019:28017"
  container_name: mongo2
  volumes:
      - haostay_dev_mongo:/haostay_dev/mongo2
  restart: always

mongo1:
  hostname: mongo1
  image: mongo:3.0.6
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27017:27017"
    - "28017:28017"
  container_name: mongo1
  volumes:
    - haostay_dev_mongo:/haostay_dev/mongo1
  links:
    - mongo2:mongo2
    - mongo3:mongo3
  restart: always

elasticsearch:
  image: elasticsearch:2.3.3
  container_name: elasticsearch
  hostname: elasticsearch
  cpu_quota: 60000
  mem_limit: 1024m
  ports:
    - "9200:9200"
    - "9300:9300"
  links:
    - mongo1:mongo1
    - mongo2:mongo2
    - mongo3:mongo3
  volumes:
    - haostay_dev_elasticsearch:/haostay_dev/elasticsearch
    - ./scripts/logging.yml:/etc/elasticsearch/logging.yml
  restart: always

# This configures the MongoDB replicaset
mongosetup:
  image: mongo:3.0.6
  links:
    - mongo1:mongo1
    - mongo2:mongo2
    - mongo3:mongo3
  volumes:
    - ./scripts:/scripts
  entrypoint: [ "/scripts/setup.sh" ]

rabbitmq:
  build: ./rabbitmq
  container_name: rabbitmq
  volumes:
   - haostay_dev_rabbitmq:/haostay_dev/rabbitmq
  ports:
   - "15674:15674"
   - "5672:5672"
   - "5671:5671"
   - "15672:15672"
   - "15671:15671"
   - "61613:61613"
   - "61614:61614"
   - "25672:25672"
   - "4369:4369"
  entrypoint: ["/usr/bin/rabbitmq-start"]
  restart: always

redis:
   #image: redis:3.2.0
   image: redis:latest
   container_name: redis
   hostname: redis
   volumes:
     - haostay_dev_redis:/haostay_dev/redis
   ports:
     - "6379:6379"
   command: redis-server --protected-mode no
   restart: always

pouchdb:
  build: ./pouchdb
  container_name: pouchdb
  volumes:
   - haostay_dev_pouchdb:/haostay_dev/pouchdb
  ports:
   - "5984:5984"
  restart: always

mongoconnector:
  build: ./mongoconnector
  container_name: mongoconnector
  cpu_quota: 40000
  links:
    - mongo1:mongo1
    - mongo2:mongo2
    - mongo3:mongo3
    - elasticsearch:elasticsearch
  entrypoint: [ "/usr/bin/mongoconnector" ]
  restart: always
