version: '2'
services:
    teachtour-web:
      build: ~/Documents/0-Code/Git/haostay-home/teachtour-web
      container_name: teachtour-web
      hostname: teachtour-web
      environment:
        MONGO_URL: "mongodb://mongo1:27017"
        PORT: 3000
        ROOT_URL: "http://teachtours.com"
        MONGO_OPLOG_URL: "mongodb://mongo1:27017/local"
        METEOR_ENV: "prod"
      expose:
        - 3000
      links:
            - redis:redis
            - mongo1:mongo1
            - mongo2:mongo2
            - mongo3:mongo3
      restart: always

    teachtour-admin:
      build: ~/Documents/0-Code/Git/haostay-home/teachtour-admin
      container_name: teachtour-admin
      hostname: teachtour-admin
      environment:
        MONGO_URL: "mongodb://mongo1:27017"
        PORT: 3001
        ROOT_URL: "http://b.teachtours.com"
        MONGO_OPLOG_URL: "mongodb://mongo1:27017/local"
        METEOR_ENV: "prod"
      expose:
        - 3001
      links:
            - redis:redis
            - mongo1:mongo1
            - mongo2:mongo2
            - mongo3:mongo3
      restart: always

    nginx:
      build: ./nginx
      container_name: nginx
      depends_on:
        - teachtour-web
        - teachtour-admin
      ports:
        - "80:80"

volumes:
  mongo:
  redis:
