version: '2'
services:

    mongodata:
        image: mongo:3.0.7
        container_name: mongodata
        volumes:
          - /db
        command: chown mongodb:mongodb /db && tail -f /dev/null

    mongo1:
        container_name: "mongo1"
        image: mongo:3.0.7
        hostname: mongo1
        ports:
            - "27017:27017"
        volumes_from:
            - mongodata

    redis:
       image: redis:3.2.0
       container_name: redis
       hostname: redis
       ports:
         - "6379:6379"
       volumes:
         - redis:/var/lib/redis
       restart: always

    rabbitdata:
      image: rabbitmq:latest
      volumes:
        - /var/lib/rabbitmq
      command: tail -f /dev/null

    rabbitmq:
        build: ./rabbitmq
        container_name: rabbitmq
        hostname: rabbitmq
        volumes_from:
         - rabbitdata
        ports:
        - "15674:15674"
        - "5672:5672"
        - "5671:5671"
        - "15672:15672"
        - "15671:15671"
        - "61613:61613"
        - "61614:61614"
        - "25672:25672"
        - "4369:4369"
        entrypoint: ["/usr/bin/rabbitmq-start"]

    teachtour-web:
      build: ~/Documents/0-Code/Git/haostay-home/teachtour-web
      container_name: teachtour-web
      hostname: teachtour-web
      environment:
        MONGO_URL: "mongodb://mongo1:27017"
        PORT: 3000
        ROOT_URL: "http://teachtours.com"
        MONGO_OPLOG_URL: "mongodb://mongo1:27017/local"
        METEOR_ENV: "stage"
      expose:
        - 3000
      links:
            - teachtour-messager:teachtour-messager
            - redis:redis
            - mongo1:mongo1
      restart: always

    teachtour-admin:
      build: ~/Documents/0-Code/Git/haostay-home/teachtour-admin
      container_name: teachtour-admin
      hostname: teachtour-admin
      environment:
        MONGO_URL: "mongodb://mongo1:27017"
        PORT: 3001
        ROOT_URL: "http://admin.teachtours.com"
        MONGO_OPLOG_URL: "mongodb://mongo1:27017/local"
        METEOR_ENV: "stage"
      expose:
        - 3001
      links:
            - teachtour-messager:teachtour-messager
            - redis:redis
            - mongo1:mongo1
      restart: always

    teachtour-org:
      build: ~/Documents/0-Code/Git/haostay-home/teachtour-org
      container_name: teachtour-org
      hostname: teachtour-org
      environment:
        MONGO_URL: "mongodb://mongo1:27017"
        PORT: 3002
        ROOT_URL: "http://b.teachtours.com"
        MONGO_OPLOG_URL: "mongodb://mongo1:27017/local"
        METEOR_ENV: "stage"
      expose:
        - 3002
      links:
            - teachtour-messager:teachtour-messager
            - redis:redis
            - mongo1:mongo1
      restart: always

    teachtour-messager:
      build: ~/Documents/0-Code/Git/haostay-home/teachtour-messager
      container_name: teachtour-messager
      hostname: teachtour-messager
      environment:
        MONGO_URL: "mongodb://mongo1:27017"
        PORT: 3003
        ROOT_URL: "http://msg.teachtours.com"
        MONGO_OPLOG_URL: "mongodb://mongo1:27017/local"
        METEOR_ENV: "stage"
      expose:
        - 3003
      links:
            - rabbitmq:rabbitmq
            - redis:redis
            - mongo1:mongo1
      restart: always


    nginx:
      build: ./nginx
      container_name: nginx
      depends_on:
        - teachtour-web
        - teachtour-admin
        - teachtour-org
        - teachtour-messager
#        - web2
#      links:
#        - web1:web1
#        - web2:web2
#      environment:
#        HOST_TARGET: "prod"
      ports:
        - "80:80"

volumes:
  mongo:
  redis:
