version: '2'
services:
    mongo2:
        container_name: "mongo2"
        image: mongo
        ports:
            - "27018:27017"
            - "28018:28017"
        command: mongod --replSet rs1 --port 27017 --journal --smallfiles
        volumes:
            - dev_mongo:/mongo2
        restart: always

    mongo3:
        container_name: "mongo3"
        image: mongo
        ports:
            - "27019:27017"
            - "28019:28017"
        command: mongod --replSet rs1 --port 27017 --journal --smallfiles
        volumes:
            - dev_mongo:/mongo3
        restart: always 

    mongo1:
        container_name: "mongo1"
        image: mongo
        ports:
            - "27017:27017"
            - "28017:28017"
        command: mongod --replSet rs1 --port 27017 --journal --smallfiles
        volumes:
            - dev_mongo:/mongo1
        links:
            - mongo2:mongo2
            - mongo3:mongo3
        restart: always

    mongo-rs-setup:
        container_name: "mongo-rs-setup"
        build: ./mongosetup
        depends_on:
            - "mongo1"
            - "mongo2"
            - "mongo3"
        links:
            - mongo1:mongo1
            - mongo2:mongo2
            - mongo3:mongo3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo1
            - MONGO2=mongo2
            - MONGO3=mongo3
            - RS=rs1
        entrypoint: [ "/setup.sh" ]

    # mongoconnector:
    #     build: ./mongoconnector
    #     container_name: mongoconnector
    #     links:
    #         - elasticsearch:elasticsearch
    #         - mongo1:mongo1
    #         - mongo2:mongo2
    #         - mongo3:mongo3
    #     entrypoint: [ "/usr/bin/mongoconnector" ]

volumes:
  dev_mongo:
  dev_elasticsearch:
  dev_rabbitmq:
  dev_redis:
  dev_redis_data:
  dev_pouchdb:
